python_questions = [
    {"Savol": "1. Python programming language qachon yaratilgan?", "a": "1989", "b": "1991", "c": "2000", "Javob": "b"},
    {"Savol": "2. Python kim tomonidan yaratilgan?", "a": "Dennis Ritchie", "b": "James Gosling", "c": "Guido van Rossum", "Javob": "c"},
    {"Savol": "3. Python o'zgaruvchilarni qanday turi bilan belgilaydi?", "a": "Static", "b": "Both", "c": "Dynamic", "Javob": "c"},
    {"Savol": "4. Python dasturlash tili nima uchun mashhur?", "a": "Oson sintaksisi", "b": "Ikkalasi ham", "c": "Keng kutubxonalar to'plami", "Javob": "b"},
    {"Savol": "5. Python'da ro'yxat elementlarini qanday tartiblash mumkin?", "a": "sorted() funksiyasi", "b": "sort() metodi", "c": "Ikkalasi ham", "Javob": "c"},
    {"Savol": "6. Python'da 'None' nima ma'noga ega?", "a": "0", "b": "Hech narsa", "c": "Bo'sh satr", "Javob": "b"},
    {"Savol": "7. Python'da qanday turi bor 'dictionary'?", "a": "Tuple", "b": "Dict", "c": "List", "Javob": "b"},
    {"Savol": "8. Python'da 'len()' funksiyasi nima qiladi?", "a": "Qiymat", "b": "O'zgaruvchi turi", "c": "Uzunlik", "Javob": "c"},
    {"Savol": "9. Python'da 'def' kalit so'zi nima uchun ishlatiladi?", "a": "Modul import qilish", "b": "Funksiya yaratish", "c": "Class yaratish", "Javob": "b"},
    {"Savol": "10. Python'da 'import' kalit so'zi nima uchun ishlatiladi?", "a": "Class yaratish", "b": "Funksiya yaratish", "c": "Modul import qilish", "Javob": "c"},
    {"Savol": "11. Python'da 'for' tsikli nima uchun ishlatiladi?", "a": "Shart bajarilganicha kodni bajarish", "b": "Bir nechta marta kodni bajarish", "c": "Funksiya chaqirish", "Javob": "b"},
    {"Savol": "12. Python'da 'while' tsikli nima uchun ishlatiladi?", "a": "Bir nechta marta kodni bajarish", "b": "Shart bajarilganicha kodni bajarish", "c": "Funksiya chaqirish", "Javob": "b"},
    {"Savol": "13. Python'da 'if' sharti nima uchun ishlatiladi?", "a": "Kodni bir marta bajarish", "b": "Shart bajarilganicha kodni bajarish", "c": "Shart to'g'ri bo'lganda kodni bajarish", "Javob": "c"},
    {"Savol": "14. Python'da 'elif' sharti nima uchun ishlatiladi?", "a": "Boshqa shartlarni tekshirish", "b": "Birinchi shart noto'g'ri bo'lganda kodni bajarish", "c": "Birinchi shart to'g'ri bo'lganda kodni bajarish", "Javob": "a"},
    {"Savol": "15. Python'da 'else' sharti nima uchun ishlatiladi?", "a": "Boshqa shartlarni tekshirish", "b": "Barcha shartlar noto'g'ri bo'lganda kodni bajarish", "c": "Birinchi shart to'g'ri bo'lganda kodni bajarish", "Javob": "b"},
    {"Savol": "16. Python'da 'list' nima?", "a": "Funksiya", "b": "O'zgaruvchilar to'plami", "c": "Modul", "Javob": "b"},
    {"Savol": "17. Python'da 'tuple' nima?", "a": "Funksiya", "b": "O'zgaruvchilar to'plami", "c": "Modul", "Javob": "b"},
    {"Savol": "18. Python'da 'dict' nima?", "a": "Funksiya", "b": "O'zgaruvchilar to'plami", "c": "Modul", "Javob": "b"},
    {"Savol": "19. Python'da 'set' nima?", "a": "Funksiya", "b": "O'zgaruvchilar to'plami", "c": "Modul", "Javob": "b"},
    {"Savol": "20. Python'da 'str' nima?", "a": "Funksiya", "b": "Matn turi", "c": "Modul", "Javob": "b"},
    {"Savol": "21. Python'da 'int' nima?", "a": "Funksiya", "b": "Butun son turi", "c": "Modul", "Javob": "b"},
    {"Savol": "22. Python'da 'float' nima?", "a": "Funksiya", "b": "Haqiqiy son turi", "c": "Modul", "Javob": "b"},
    {"Savol": "23. Python'da 'bool' nima?", "a": "Funksiya", "b": "Mantiqiy qiymat turi", "c": "Modul", "Javob": "b"},
    {"Savol": "24. Python'da 'type()' funksiyasi nima qiladi?", "a": "Uzunlik", "b": "O'zgaruvchi turi", "c": "Qiymat", "Javob": "b"},
    {"Savol": "25. Python'da 'print()' funksiyasi nima qiladi?", "a": "O'zgaruvchi turi", "b": "Qiymatni konsolga chiqarish", "c": "Uzunlik", "Javob": "b"},
    {"Savol": "26. Python'da 'input()' funksiyasi nima qiladi?", "a": "Foydalanuvchidan ma'lumot olish", "b": "Ma'lumotni konsolga chiqarish", "c": "Fayl ochish", "Javob": "a"},
    {"Savol": "27. Python'da 'open()' funksiyasi nima uchun ishlatiladi?", "a": "Fayl ochish", "b": "Foydalanuvchidan ma'lumot olish", "c": "Ma'lumotni konsolga chiqarish", "Javob": "a"},
    {"Savol": "28. Python'da 'close()' funksiyasi nima uchun ishlatiladi?", "a": "Fayl yopish", "b": "Fayl ochish", "c": "Foydalanuvchidan ma'lumot olish", "Javob": "a"},
    {"Savol": "29. Python'da 'read()' funksiyasi nima uchun ishlatiladi?", "a": "Fayldan ma'lumot o'qish", "b": "Fayl yopish", "c": "Fayl ochish", "Javob": "a"},
    {"Savol": "30. Python'da 'write()' funksiyasi nima uchun ishlatiladi?", "a": "Faylga ma'lumot yozish", "b": "Fayldan ma'lumot o'qish", "c": "Fayl yopish", "Javob": "a"},
    {"Savol": "31. Python'da 'append()' funksiyasi nima uchun ishlatiladi?", "a": "Ro'yxatga element qo'shish", "b": "Faylga ma'lumot yozish", "c": "Fayldan ma'lumot o'qish", "Javob": "a"},
    {"Savol": "32. Python'da 'remove()' funksiyasi nima uchun ishlatiladi?", "a": "Ro'yxatdan element olib tashlash", "b": "Ro'yxatga element qo'shish", "c": "Faylga ma'lumot yozish", "Javob": "a"},
    {"Savol": "33. Python'da 'pop()' funksiyasi nima uchun ishlatiladi?", "a": "Ro'yxatdan element olib tashlash", "b": "Ro'yxatga element qo'shish", "c": "Faylga ma'lumot yozish", "Javob": "a"},
    {"Savol": "34. Python'da 'split()' funksiyasi nima uchun ishlatiladi?", "a": "Matnni ro'yxatga aylantirish", "b": "Ro'yxatdan element olib tashlash", "c": "Ro'yxatga element qo'shish", "Javob": "a"},
    {"Savol": "35. Python'da 'join()' funksiyasi nima uchun ishlatiladi?", "a": "Ro'yxatni matnga aylantirish", "b": "Matnni ro'yxatga aylantirish", "c": "Ro'yxatdan element olib tashlash", "Javob": "a"},
    {"Savol": "36. Python'da 'range()' funksiyasi nima uchun ishlatiladi?", "a": "Sonlar orasidagi oraliqni yaratish", "b": "Ro'yxatni matnga aylantirish", "c": "Matnni ro'yxatga aylantirish", "Javob": "a"},
    {"Savol": "37. Python'da 'enumerate()' funksiyasi nima uchun ishlatiladi?", "a": "Ro'yxat elementlarini indeksi bilan birga qaytarish", "b": "Sonlar orasidagi oraliqni yaratish", "c": "Ro'yxatni matnga aylantirish", "Javob": "a"},
    {"Savol": "38. Python'da 'zip()' funksiyasi nima uchun ishlatiladi?", "a": "Ikki yoki undan ko'p ro'yxatlarni birga birlashtirish", "b": "Ro'yxat elementlarini indeksi bilan birga qaytarish", "c": "Sonlar orasidagi oraliqni yaratish", "Javob": "a"},
    {"Savol": "39. Python'da 'filter()' funksiyasi nima uchun ishlatiladi?", "a": "Ro'yxat elementlarini shartga ko'ra filtrlash", "b": "Ikki yoki undan ko'p ro'yxatlarni birga birlashtirish", "c": "Ro'yxat elementlarini indeksi bilan birga qaytarish", "Javob": "a"},
    {"Savol": "40. Python'da 'map()' funksiyasi nima uchun ishlatiladi?", "a": "Ro'yxat elementlariga funksiyani tatbiq etish", "b": "Ro'yxat elementlarini shartga ko'ra filtrlash", "c": "Ikki yoki undan ko'p ro'yxatlarni birga birlashtirish", "Javob": "a"},
    {"Savol": "41. Python'da 'lambda' ifodasi nima uchun ishlatiladi?", "a": "Anonim funksiyani yaratish", "b": "Ro'yxat elementlariga funksiyani tatbiq etish", "c": "Ro'yxat elementlarini shartga ko'ra filtrlash", "Javob": "a"},
    {"Savol": "42. Python'da 'try/except' bloki nima uchun ishlatiladi?", "a": "Xatoliklarni tutib olish", "b": "Anonim funksiyani yaratish", "c": "Ro'yxat elementlariga funksiyani tatbiq etish", "Javob": "a"},
    {"Savol": "43. Python'da 'raise' kalit so'zi nima uchun ishlatiladi?", "a": "Xatolikni qo'llab-quvvatlash", "b": "Xatoliklarni tutib olish", "c": "Anonim funksiyani yaratish", "Javob": "a"},
    {"Savol": "44. Python'da 'assert' kalit so'zi nima uchun ishlatiladi?", "a": "Shartni tekshirish", "b": "Xatolikni qo'llab-quvvatlash", "c": "Xatoliklarni tutib olish", "Javob": "a"},
    {"Savol": "45. Python'da 'with' kalit so'zi nima uchun ishlatiladi?", "a": "Kontekstni boshqarish", "b": "Shartni tekshirish", "c": "Xatolikni qo'llab-quvvatlash", "Javob": "a"},
    {"Savol": "46. Python'da 'class' kalit so'zi nima uchun ishlatiladi?", "a": "Klass yaratish", "b": "Kontekstni boshqarish", "c": "Shartni tekshirish", "Javob": "a"},
    {"Savol": "47. Python'da 'self' kalit so'zi nima uchun ishlatiladi?", "a": "Klassning o'ziga murojaat qilish", "b": "Klass yaratish", "c": "Kontekstni boshqarish", "Javob": "a"},
    {"Savol": "48. Python'da 'super' kalit so'zi nima uchun ishlatiladi?", "a": "Ota klassga murojaat qilish", "b": "Klassning o'ziga murojaat qilish", "c": "Klass yaratish", "Javob": "a"},
    {"Savol": "49. Python'da 'global' kalit so'zi nima uchun ishlatiladi?", "a": "Global o'zgaruvchiga murojaat qilish", "b": "Ota klassga murojaat qilish", "c": "Klassning o'ziga murojaat qilish", "Javob": "a"},
    {"Savol": "50. Python'da 'nonlocal' kalit so'zi nima uchun ishlatiladi?", "a": "Ichki funksiyadan tashqi o'zgaruvchiga murojaat qilish", "b": "Global o'zgaruvchiga murojaat qilish", "c": "Ota klassga murojaat qilish", "Javob": "a"},
]

django_questions = [
    {"Savol": "1. Django nima uchun ishlatiladi?", "a": "Veb-ilovalarni yaratish", "b": "Desktop ilovalarni yaratish", "c": "Mobil ilovalarni yaratish", "Javob": "a"},
    {"Savol": "2. Django qachon yaratilgan?", "a": "2005", "b": "2000", "c": "2010", "Javob": "a"},
    {"Savol": "3. Django kim tomonidan yaratilgan?", "a": "Guido van Rossum", "b": "Adrian Holovaty va Simon Willison", "c": "Mark Zuckerberg", "Javob": "b"},
    {"Savol": "4. Django'da 'view' nima uchun ishlatiladi?", "a": "Ma'lumotlarni bazadan olish", "b": "Foydalanuvchi so'rovi bilan ishlash", "c": "Ma'lumotlarni bazaga saqlash", "Javob": "b"},
    {"Savol": "5. Django'da 'model' nima uchun ishlatiladi?", "a": "Ma'lumotlarni bazadan olish", "b": "Foydalanuvchi so'rovi bilan ishlash", "c": "Ma'lumotlarni bazaga saqlash", "Javob": "a"},
    {"Savol": "6. Django'da 'template' nima uchun ishlatiladi?", "a": "HTML sahifalarni yaratish", "b": "Ma'lumotlarni bazadan olish", "c": "Foydalanuvchi so'rovi bilan ishlash", "Javob": "a"},
    {"Savol": "7. Django'da 'url' nima uchun ishlatiladi?", "a": "URL manzillarni boshqarish", "b": "HTML sahifalarni yaratish", "c": "Ma'lumotlarni bazadan olish", "Javob": "a"},
    {"Savol": "8. Django'da 'admin' nima uchun ishlatiladi?", "a": "Veb-ilovaning boshqaruv panelini yaratish", "b": "URL manzillarni boshqarish", "c": "HTML sahifalarni yaratish", "Javob": "a"},
    {"Savol": "9. Django'da 'middleware' nima uchun ishlatiladi?", "a": "So'rov va javob oqimini boshqarish", "b": "Veb-ilovaning boshqaruv panelini yaratish", "c": "URL manzillarni boshqarish", "Javob": "a"},
    {"Savol": "10. Django'da 'ORM' nima uchun ishlatiladi?", "a": "Ma'lumotlar bazasi bilan ishlash", "b": "So'rov va javob oqimini boshqarish", "c": "Veb-ilovaning boshqaruv panelini yaratish", "Javob": "a"},
    {"Savol": "11. Django'da 'migrate' nima uchun ishlatiladi?", "a": "Ma'lumotlar bazasidagi o'zgarishlarni amalga oshirish", "b": "Ma'lumotlar bazasi bilan ishlash", "c": "So'rov va javob oqimini boshqarish", "Javob": "a"},
    {"Savol": "12. Django'da 'makemigrations' nima uchun ishlatiladi?", "a": "Ma'lumotlar bazasidagi o'zgarishlarni yozib olish", "b": "Ma'lumotlar bazasidagi o'zgarishlarni amalga oshirish", "c": "Ma'lumotlar bazasi bilan ishlash", "Javob": "a"},
    {"Savol": "13. Django'da 'runserver' nima uchun ishlatiladi?", "a": "Ishlab chiqarish serverini ishga tushirish", "b": "Ma'lumotlar bazasidagi o'zgarishlarni yozib olish", "c": "Ma'lumotlar bazasidagi o'zgarishlarni amalga oshirish", "Javob": "a"},
    {"Savol": "14. Django'da 'startapp' nima uchun ishlatiladi?", "a": "Yangi ilova yaratish", "b": "Ishlab chiqarish serverini ishga tushirish", "c": "Ma'lumotlar bazasidagi o'zgarishlarni yozib olish", "Javob": "a"},
    {"Savol": "15. Django'da 'startproject' nima uchun ishlatiladi?", "a": "Yangi loyiha yaratish", "b": "Yangi ilova yaratish", "c": "Ishlab chiqarish serverini ishga tushirish", "Javob": "a"},
    {"Savol": "16. Django'da 'settings.py' nima uchun ishlatiladi?", "a": "Loyiha sozlamalarini saqlash", "b": "Yangi loyiha yaratish", "c": "Yangi ilova yaratish", "Javob": "a"},
    {"Savol": "17. Django'da 'urls.py' nima uchun ishlatiladi?", "a": "URL manzillarni boshqarish", "b": "Loyiha sozlamalarini saqlash", "c": "Yangi loyiha yaratish", "Javob": "a"},
    {"Savol": "18. Django'da 'views.py' nima uchun ishlatiladi?", "a": "Foydalanuvchi so'rovi bilan ishlash", "b": "URL manzillarni boshqarish", "c": "Loyiha sozlamalarini saqlash", "Javob": "a"},
    {"Savol": "19. Django'da 'models.py' nima uchun ishlatiladi?", "a": "Ma'lumotlar modelini yaratish", "b": "Foydalanuvchi so'rovi bilan ishlash", "c": "URL manzillarni boshqarish", "Javob": "a"},
    {"Savol": "20. Django'da 'forms.py' nima uchun ishlatiladi?", "a": "Foydalanuvchi formasini yaratish", "b": "Ma'lumotlar modelini yaratish", "c": "Foydalanuvchi so'rovi bilan ishlash", "Javob": "a"},
    {"Savol": "21. Django'da 'admin.py' nima uchun ishlatiladi?", "a": "Admin panelini sozlash", "b": "Foydalanuvchi formasini yaratish", "c": "Ma'lumotlar modelini yaratish", "Javob": "a"},
    {"Savol": "22. Django'da 'manage.py' nima uchun ishlatiladi?", "a": "Loyiha boshqarish buyruqlarini bajarish", "b": "Admin panelini sozlash", "c": "Foydalanuvchi formasini yaratish", "Javob": "a"},
    {"Savol": "23. Django'da 'test.py' nima uchun ishlatiladi?", "a": "Testlarni yaratish", "b": "Loyiha boshqarish buyruqlarini bajarish", "c": "Admin panelini sozlash", "Javob": "a"},
    {"Savol": "24. Django'da 'csrf_token' nima uchun ishlatiladi?", "a": "Xavfsizlikni ta'minlash", "b": "Testlarni yaratish", "c": "Loyiha boshqarish buyruqlarini bajarish", "Javob": "a"},
    {"Savol": "25. Django REST framework'da 'permissions' nima uchun ishlatiladi?","a": "Foydalanuvchilarga ma'lumotlarni o'qish, yozish, o'chirish va o'zgartirish huquqlarini boshqarish","b": "Ma'lumotlarni bazadan olish","c": "Saytning interfeysini yaratish","Javob": "a"},
    {"Savol": "26. Django'da 'HttpResponse' nima uchun ishlatiladi?", "a": "HTTP javobini yaratish", "b": "HTTP so'rovini yaratish", "c": "HTTP so'rovini qaytarish", "Javob": "a"},
    {"Savol": "27. Django'da 'JsonResponse' nima uchun ishlatiladi?", "a": "JSON javobini yaratish", "b": "JSON so'rovini yaratish", "c": "JSON so'rovini qaytarish", "Javob": "a"},
    {"Savol": "28. Django'da 'redirect' nima uchun ishlatiladi?", "a": "Foydalanuvchini boshqa URL-ga yo'naltirish", "b": "HTTP javobini yaratish", "c": "JSON javobini yaratish", "Javob": "a"},
    {"Savol": "29. Django'da 'render' nima uchun ishlatiladi?", "a": "HTML sahifani yaratish va javob sifatida qaytarish", "b": "Foydalanuvchini boshqa URL-ga yo'naltirish", "c": "HTTP javobini yaratish", "Javob": "a"},
    {"Savol": "30. Django'da 'get_object_or_404' nima uchun ishlatiladi?", "a": "Ob'ekt topilsa uni qaytarish, aks holda 404 xatolikni qaytarish", "b": "HTML sahifani yaratish va javob sifatida qaytarish", "c": "Foydalanuvchini boshqa URL-ga yo'naltirish", "Javob": "a"},
    {"Savol": "31. Django'da 'login_required' nima uchun ishlatiladi?", "a": "Foydalanuvchi tizimga kirdimi yoki yo'qmi tekshirish", "b": "Ob'ekt topilsa uni qaytarish, aks holda 404 xatolikni qaytarish", "c": "HTML sahifani yaratish va javob sifatida qaytarish", "Javob": "a"},
    {"Savol": "32. Django'da 'User' modeli nima uchun ishlatiladi?", "a": "Foydalanuvchilar ma'lumotlarini saqlash", "b": "Foydalanuvchi tizimga kirdimi yoki yo'qmi tekshirish", "c": "Ob'ekt topilsa uni qaytarish, aks holda 404 xatolikni qaytarish", "Javob": "a"},
    {"Savol": "33. Django'da 'Group' modeli nima uchun ishlatiladi?", "a": "Foydalanuvchilar guruhlarini saqlash", "b": "Foydalanuvchilar ma'lumotlarini saqlash", "c": "Foydalanuvchi tizimga kirdimi yoki yo'qmi tekshirish", "Javob": "a"},
    {"Savol": "34. Django'da 'Permission' modeli nima uchun ishlatiladi?", "a": "Foydalanuvchilar huquqlarini saqlash", "b": "Foydalanuvchilar guruhlarini saqlash", "c": "Foydalanuvchilar ma'lumotlarini saqlash", "Javob": "a"},
    {"Savol": "35. Django'da 'authenticate' funksiyasi nima uchun ishlatiladi?", "a": "Foydalanuvchi ma'lumotlarini tekshirish", "b": "Foydalanuvchilar huquqlarini saqlash", "c": "Foydalanuvchilar guruhlarini saqlash", "Javob": "a"},
    {"Savol": "36. Django'da 'login' funksiyasi nima uchun ishlatiladi?", "a": "Foydalanuvchini tizimga kirish", "b": "Foydalanuvchi ma'lumotlarini tekshirish", "c": "Foydalanuvchilar huquqlarini saqlash", "Javob": "a"},
    {"Savol": "37. Django'da 'logout' funksiyasi nima uchun ishlatiladi?", "a": "Foydalanuvchini tizimdan chiqarish", "b": "Foydalanuvchini tizimga kirish", "c": "Foydalanuvchi ma'lumotlarini tekshirish", "Javob": "a"},
    {"Savol": "38. Django'da 'session' nima uchun ishlatiladi?", "a": "Foydalanuvchi sessiyasini boshqarish", "b": "Foydalanuvchini tizimdan chiqarish", "c": "Foydalanuvchini tizimga kirish", "Javob": "a"},
    {"Savol": "39. Django'da 'cookie' nima uchun ishlatiladi?", "a": "Foydalanuvchi ma'lumotlarini brauzerda saqlash", "b": "Foydalanuvchi sessiyasini boshqarish", "c": "Foydalanuvchini tizimdan chiqarish", "Javob": "a"},
    {"Savol": "40. Django'da 'QuerySet' nima uchun ishlatiladi?", "a": "Ma'lumotlar bazasiga so'rov yuborish", "b": "Foydalanuvchi ma'lumotlarini brauzerda saqlash", "c": "Foydalanuvchi sessiyasini boshqarish", "Javob": "a"},
    {"Savol": "41. Django'da 'filter' funksiyasi nima uchun ishlatiladi?", "a": "Ma'lumotlar bazasidan ma'lumotlarni filtrlash", "b": "Ma'lumotlar bazasiga so'rov yuborish", "c": "Foydalanuvchi ma'lumotlarini brauzerda saqlash", "Javob": "a"},
    {"Savol": "42. Django'da 'exclude' funksiyasi nima uchun ishlatiladi?", "a": "Ma'lumotlar bazasidan ma'lumotlarni chiqarib tashlash", "b": "Ma'lumotlar bazasidan ma'lumotlarni filtrlash", "c": "Ma'lumotlar bazasiga so'rov yuborish", "Javob": "a"},
    {"Savol": "43. Django'da 'order_by' funksiyasi nima uchun ishlatiladi?", "a": "Ma'lumotlar bazasidan ma'lumotlarni tartiblash", "b": "Ma'lumotlar bazasidan ma'lumotlarni chiqarib tashlash", "c": "Ma'lumotlar bazasidan ma'lumotlarni filtrlash", "Javob": "a"},
    {"Savol": "44. Django'da 'annotate' funksiyasi nima uchun ishlatiladi?", "a": "Ma'lumotlar bazasidan ma'lumotlarni hisoblash", "b": "Ma'lumotlar bazasidan ma'lumotlarni tartiblash", "c": "Ma'lumotlar bazasidan ma'lumotlarni chiqarib tashlash", "Javob": "a"},
    {"Savol": "45. Django'da 'aggregate' funksiyasi nima uchun ishlatiladi?", "a": "Ma'lumotlar bazasidan ma'lumotlarni yig'indisini hisoblash", "b": "Ma'lumotlar bazasidan ma'lumotlarni hisoblash", "c": "Ma'lumotlar bazasidan ma'lumotlarni tartiblash", "Javob": "a"},
    {"Savol": "46. Django'da 'F' ob'ekti nima uchun ishlatiladi?", "a": "Ma'lumotlar bazasidagi qiymatlarni to'g'ridan-to'g'ri ishlatish", "b": "Ma'lumotlar bazasidan ma'lumotlarni yig'indisini hisoblash", "c": "Ma'lumotlar bazasidan ma'lumotlarni hisoblash", "Javob": "a"},
    {"Savol": "47. Django'da 'Q' ob'ekti nima uchun ishlatiladi?", "a": "Murakkab so'rovlar yaratish", "b": "Ma'lumotlar bazasidagi qiymatlarni to'g'ridan-to'g'ri ishlatish", "c": "Ma'lumotlar bazasidan ma'lumotlarni yig'indisini hisoblash", "Javob": "a"},
    {"Savol": "48. Django'da 'Prefetch' ob'ekti nima uchun ishlatiladi?", "a": "Ma'lumotlarni oldindan yuklab olish", "b": "Murakkab so'rovlar yaratish", "c": "Ma'lumotlar bazasidagi qiymatlarni to'g'ridan-to'g'ri ishlatish", "Javob": "a"},
    {"Savol": "49. Django'da 'select_related' funksiyasi nima uchun ishlatiladi?", "a": "Bog'liq ma'lumotlarni bir so'rov bilan olish", "b": "Ma'lumotlarni oldindan yuklab olish", "c": "Murakkab so'rovlar yaratish", "Javob": "a"},
    {"Savol": "50. Django'da 'prefetch_related' funksiyasi nima uchun ishlatiladi?", "a": "Bog'liq ma'lumotlarni bir nechta so'rov bilan olish", "b": "Bog'liq ma'lumotlarni bir so'rov bilan olish", "c": "Ma'lumotlarni oldindan yuklab olish", "Javob": "a"}
]